name: 菜玩网自动签到

on:
  schedule:
    # 将任务提前到 UTC 15:59 (北京时间 23:59) 启动。
    # 这为脚本的启动和准备工作提供了 60 秒的窗口时间。
    - cron: '59 15 * * *'
  
  workflow_dispatch:
    # 保留此项，以便你可以随时手动点击 "Run workflow" 按钮来触发此工作流，方便测试。

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx

      - name: Run check-in script
        env:
          CAIWAN_COOKIE: ${{ secrets.CAIWAN_COOKIE }}
        run: python checkin.py
